"""create token black list table

Revision ID: 437aeceee1d5
Revises: 0dd8c8fdc031
Create Date: 2024-09-05 01:17:11.607446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import uuid
from datetime import datetime, timezone


# revision identifiers, used by Alembic.
revision: str = '437aeceee1d5'
down_revision: Union[str, None] = '0dd8c8fdc031'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token_blacklist',
        sa.Column('id', sa.UUID(as_uuid=True), primary_key=True, default=uuid.uuid4),
        sa.Column('token', sa.String(), nullable=False, unique=True, index=True),
        sa.Column('blacklisted_on', sa.DateTime(), default=datetime.now(timezone.utc), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('token_blacklist')
    # ### end Alembic commands ###
